### ISSUE TITLE
Parse special characters

### ISSUE THREAD

**Issue by SalvatoreAD** [gcharita/XMLMapper#10] opened 2018-04-05 15:50 UTC
I have problem parsing this special characters (&amp;nbsp;&lt;br /&gt;). In the xml tags there are also these symbols and html code. Can You help me?

**Comment by gcharita** [comment] 2018-04-06 13:00
This situation also mentioned in #4.
Inner text of an element must to be XML encoded. For more details you can see [this question](https://stackoverflow.com/questions/730133/invalid-characters-in-xml) in stackoverflow and the [XML entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references) in wikipedia.

`XMLMapper` uses already the public property `xmlEncodedString` ([String+XMLParser.swift](https://github.com/gcharita/XMLMapper/blob/master/XMLMapper/Classes/String%2BXMLParser.swift)) to XML encode the inner text of tags in serialization proccess.

**Comment by gcharita** [comment] 2018-04-06 13:02
Duplicate of #4

**Closed as completed** 2018-04-07 14:30 UTC
Labels: duplicate
